#!/bin/bash
echo ">>>>>>>>>>> BUILD HOOK START - creating symlink for book photo"
mkdir -p $OPENSHIFT_DATA_DIR'uploads'
ln -sf $OPENSHIFT_DATA_DIR'uploads' $OPENSHIFT_REPO_DIR'public/uploads'
echo ">>>>>>>>>>> BUILD HOOK END - creating symlink for book photo"