#!/bin/bash

echo "Starting deploy"

pushd ${OPENSHIFT_REPO_DIR} > /dev/null

echo "Running bundle exec rake db:migrate RAILS_ENV=production"

bundle exec rake db:migrate RAILS_ENV="production"

echo "Running bundle exec rake db:seed RAILS_ENV=production"

bundle exec rake db:seed RAILS_ENV="production"

popd > /dev/null